### ISSUE TITLE
[Sugestão] - Fazer uma validação de arquivo modificado

### ISSUE THREAD

**Issue by leodevopscloud** [leoviana00/GitContributionOpenSource#70]
**Sua sugestão está relacionada a um problema? Por favor descreva**
Assim como ja é realizado uma verificação no tituli do PR , pode ser feito uma validação do arquivo específico modificado, assim caso outro arquivo seja modificado, o PR não segue.

**Descreva a solução que você deseja**
N/A

**Descreva as alternativas que você considerou**
Step de validação no ACtions

**Contexto adicional**
N/A

**Você tem interesse em trabalhar nisso?**
- [x] Sim
- [ ] Não

**Screenshots**
N/A

**Comment by leoviana00** [comment]
Vamos planejar esse step adicional essa semana
